apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-svc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-svc
  template:
    metadata:
      labels:
        app: order-svc
    spec:
      containers:
        - name: order-svc
          image: thecodealchemist/order-svc:1.4-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          envFrom:
            - configMapRef:
                name: order-svc-config
            - secretRef:
                name: order-svc-secret
          livenessProbe:
            httpGet:
              path: "/actuator/health/liveness"
              port: 8080
            failureThreshold: 30
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: "/actuator/health/readiness"
              port: 8080
            failureThreshold: 30
            periodSeconds: 3
