spring:
  application:
    name: order-service

management:
  endpoints:
    web:
      exposure:
        include: health, info
app:
  message: Demo application
  apiToken:


inventory:
  service:
    url: http://inventory-service:8080